### ISSUE TITLE
Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by marco-cinalli** [kijai/ComfyUI-MMAudio#14]
I have this error when running MMAudioFeatureUtilsLoader.

!!! Exception during processing !!! Error while deserializing header: HeaderTooLarge
Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-MMAudio/nodes.py", line 222, in loadmodel
    synchformer_sd = load_torch_file(synchformer_path, device=offload_device)
  File "/workspace/ComfyUI/comfy/utils.py", line 36, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/usr/local/lib/python3.10/site-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

I am running on a VM on Runpod with Python 3.10.9, torch 2.5.1+cu124 and all related dependencies, I am using the workflow in examples.

**Comment by kijai** [comment]
Header error like that means the file it's trying to load is corrupt, in this case it looks like it's the syncformer model file.

**Comment by marco-cinalli** [comment]
thanks a lot! So straightforward... There was and error in my script, in the part downloading the models. For people that are also using Runpod or other Virtual Machines on Linux, I copy here the correct sh commands to download the models:

wget -P /workspace/ComfyUI/models/mmaudio https://huggingface.co/Kijai/MMAudio_safetensors/resolve/main/apple_DFN5B-CLIP-ViT-H-14-384_fp16.safetensors
wget -P /workspace/ComfyUI/models/mmaudio https://huggingface.co/Kijai/MMAudio_safetensors/resolve/main/mmaudio_large_44k_v2_fp16.safetensors
wget -P /workspace/ComfyUI/models/mmaudio https://huggingface.co/Kijai/MMAudio_safetensors/resolve/main/mmaudio_synchformer_fp16.safetensors
wget -P /workspace/ComfyUI/models/mmaudio https://huggingface.co/Kijai/MMAudio_safetensors/resolve/main/mmaudio_vae_44k_fp16.safetensors
