### ISSUE TITLE
MMAudioFeatureUtilsLoader invalid load key, '\xb8'.

### ISSUE THREAD

**Issue by magicwang1111** [kijai/ComfyUI-MMAudio#2]
got prompt
!!! Exception during processing !!! invalid load key, '\xb8'.
Traceback (most recent call last):
  File "/data/wangxi/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/wangxi/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/wangxi/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/data/wangxi/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/wangxi/ComfyUI/custom_nodes/ComfyUI-MMAudio/nodes.py", line 215, in loadmodel
    synchformer_sd = load_torch_file(synchformer_path, device=offload_device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/wangxi/ComfyUI/comfy/utils.py", line 43, in load_torch_file
    pl_sd = torch.load(ckpt, map_location=device, pickle_module=comfy.checkpoint_pickle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/wangxi/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 24, in torch_wrapper
    return orig_torch_load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/wangxi/miniconda3/envs/comfyuimain/lib/python3.11/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/wangxi/miniconda3/envs/comfyuimain/lib/python3.11/site-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '\xb8'.

Prompt executed in 0.00 seconds

**Comment by kijai** [comment]
Nodes up to date? Sounds like trying to load .safetensors with old version of nodes where it wasn't supported yet.

**Comment by magicwang1111** [comment]
(comfyuimain) wangxi@4090-algo-1:/data/wangxi/ComfyUI$ pip show torch
Name: torch
Version: 2.5.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /data/wangxi/miniconda3/envs/comfyuimain/lib/python3.11/site-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: accelerate, auto_gptq, ComfyUI-EasyNodes, controlnet-aux, face_alignment, facexlib, fairscale, flash_attn, kornia, lpips, ltx-video, open_clip_torch, peft, pytorch-lightning, spandrel, timm, torchaudio, torchdiffeq, torchmetrics, torchsde, torchvision, transparent-background, ultralytics, ultralytics-thop, xformers
(comfyuimain) wangxi@4090-algo-1:/data/wangxi/ComfyUI$
commit d77f511c6593bcbd4e65ef6e1f7bed4741801e47 (HEAD -> main, origin/main, origin/HEAD)
Author: kijai <40791699+kijai@users.noreply.github.com>
Date:   Thu Dec 12 00:09:52 2024 +0200


have update  to latest

**Comment by magicwang1111** [comment]
> Nodes up to date? Sounds like trying to load .safetensors with old version of nodes where it wasn't supported yet.

![image](https://github.com/user-attachments/assets/3e01b17b-1d16-468e-b337-169d9186b14c)
