### ISSUE TITLE
The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).（已解决）

### ISSUE THREAD

**Issue by xile-INFP** [kijai/ComfyUI-MMAudio#9]
!!! Exception during processing !!! The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-MMAudio\nodes.py", line 334, in sample
    audios = generate(clip_frames,
  File "E:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-MMAudio\mmaudio\eval_utils.py", line 58, in generate
    text_features = feature_utils.encode_text(text)
  File "E:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-MMAudio\mmaudio\model\utils\features_utils.py", line 128, in encode_text
    return self.clip_model.encode_text(tokens, normalize=True)
  File "E:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-MMAudio\mmaudio\model\utils\features_utils.py", line 25, in new_encode_text
    x = self.transformer(x, attn_mask=self.attn_mask)
  File "E:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.4\python\lib\site-packages\open_clip\transformer.py", line 324, in forward
    x = r(x, attn_mask=attn_mask)
  File "E:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.4\python\lib\site-packages\open_clip\transformer.py", line 241, in forward
    x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
  File "E:\ComfyUI-aki-v1.4\python\lib\site-packages\open_clip\transformer.py", line 227, in attention
    return self.attn(
  File "E:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\activation.py", line 1368, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "E:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\functional.py", line 6131, in multi_head_attention_forward
    raise RuntimeError(
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).

**Comment by xile-INFP** [comment]
我把open_clip_torch升级到2.29就可以了，已解决！
